school:
  path: /school
  controller: App\Controller\SchoolController::school

create_school:
   path: /school/create
   controller: App\Controller\SchoolController::create_school

delete_school:
   path: /school/delete/{id}
   controller: App\Controller\SchoolController::delete_school

update_school:
   path: /school/update/{id}
   controller: App\Controller\SchoolController::update_school

school_by_id:
   path: /school/{id}
   controller: App\Controller\SchoolController::school_by_id